Single DML POST API for all operations with Multi Collection Support
jessebenson/service-fabric-queryable pull request #4
Opened 2017-08-11 22:44 UTC by tushardhadiwal

2017-08-11 22:47 UTC, jessebenson commented
@jdhuntington @andrewjamconrad

2017-08-14 23:40 UTC, jessebenson commented on src/Microsoft.ServiceFabric.Services.Queryable/Controller/QueryableController.cs
> +								finalResult[p].Status = row; ;
(nit): extra semi-colon.

2017-08-14 23:40 UTC, jessebenson commented on src/Microsoft.ServiceFabric.Services.Queryable/Query/DmlResult.cs
> +		public string collection { get; set; }
(nit):  can you make this capitalized "Collection"

2017-08-14 23:48 UTC, jessebenson requested changes

2017-08-14 23:48 UTC, jessebenson commented on src/Microsoft.ServiceFabric.Services.Queryable/Controller/QueryableController.cs
> +					for (int i = 0; i < obj.Length; i++)
You can replace the majority of this code (e.g. remove this for loop and 'preMap') with:

var partitionMap = obj.GroupBy(o => o.PartitionId);
foreach (var partition in partitionMap)
{
    var partitionId = partition.Key;
    foreach (ValueViewModel item in partition)
    {
         // ... code here to process one item within 'partitionId'
    }
}

2017-08-14 23:48 UTC, jessebenson commented on src/Microsoft.ServiceFabric.Services.Queryable/Controller/ValueViewModel.cs
> +		public string Operation { get; set; }
You should make Operation an enum.  The front-end just has to send strings just like it does.  Json (Newtonsoft) will deserialize it correctly.

public enum Operation
{
     Add,
     Update,
     Delete,
}

2017-08-15 00:02 UTC, tushardhadiwal commented on src/Microsoft.ServiceFabric.Services.Queryable/Controller/QueryableController.cs
> +					for (int i = 0; i < obj.Length; i++)
Sometimes partitionID does not exist in incoming data, in that case I generate a random partitionId and assign it right there, and then grouping happens. And for that we anyways have to loop at least  once through the data, so we might as well map it in the same loop.

2017-08-15 00:04 UTC, tushardhadiwal commented on src/Microsoft.ServiceFabric.Services.Queryable/Query/DmlResult.cs
> +		public string collection { get; set; }
Done.

2017-08-15 00:04 UTC, tushardhadiwal commented on src/Microsoft.ServiceFabric.Services.Queryable/Controller/QueryableController.cs
> +								finalResult[p].Status = row; ;
Done

2017-08-15 00:04 UTC, tushardhadiwal commented on src/Microsoft.ServiceFabric.Services.Queryable/Controller/ValueViewModel.cs
> +		public string Operation { get; set; }
Done.

2017-08-15 17:54 UTC, merged